import { useCallback, useEffect, useState } from 'react'
import { Activity, AlertTriangle, ArrowLeft, CheckCircle2, RefreshCw, Server, XCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { getMonitoringSnapshot, type MonitoringSnapshot } from '@/services/system'
import { listIngestionJobs, type IngestionJob } from '@/services/ingestion'

const stateLabel = (value: string) => value === 'healthy' ? '正常' : value === 'unavailable' ? '不可用' : '需关注'

export default function MonitoringApp() {
  const [snapshot, setSnapshot] = useState<MonitoringSnapshot | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [providerId, setProviderId] = useState('')
  const [days, setDays] = useState('1')
  const [ingestionJobs, setIngestionJobs] = useState<IngestionJob[]>([])
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextSnapshot, jobs] = await Promise.all([getMonitoringSnapshot(Number(days), providerId.trim() || undefined), listIngestionJobs()]); setSnapshot(nextSnapshot); setIngestionJobs(jobs) } catch { setError('监控快照或插件任务读取失败，请确认本地 Agent 已连接。') } finally { setLoading(false) } }, [days, providerId])
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer) }, [load])
  const health = snapshot?.health.status
  return <div className="h-full overflow-auto bg-surface px-5 py-6 md:px-8"><div className="mx-auto max-w-5xl">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><Link to="/apps" aria-label="返回应用" className="mt-1 rounded-lg p-2 text-on-surface-variant hover:bg-surface-container"><ArrowLeft className="h-4 w-4" /></Link><div><div className="text-[11px] font-medium tracking-[0.16em] text-on-surface-variant">RUNTIME OBSERVABILITY</div><h1 className="mt-1 font-display text-2xl font-bold text-on-surface">监控应用</h1><p className="mt-2 text-sm text-on-surface-variant">用统一快照观察模型、任务、插件和本机运行环境。</p></div></div><Button variant="outline" size="sm" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? 'mr-2 h-4 w-4 animate-spin' : 'mr-2 h-4 w-4'} />刷新</Button></div>
    {error && <div className="mt-5 rounded-xl border border-error/30 bg-error/5 px-4 py-3 text-sm text-error">{error}</div>}
    <Card className="mt-5"><CardContent className="flex flex-wrap items-end gap-3 pt-5"><div className="min-w-44"><label className="text-xs text-on-surface-variant">统计窗口</label><Select value={days} onValueChange={setDays}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent>{[['1', '最近 1 天'], ['7', '最近 7 天'], ['14', '最近 14 天'], ['31', '最近 31 天']].map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className="min-w-56 flex-1"><label htmlFor="monitor-provider" className="text-xs text-on-surface-variant">供应商筛选</label><Input id="monitor-provider" value={providerId} onChange={event => setProviderId(event.target.value)} placeholder="provider_id（留空为全部）" className="mt-1" /></div><Button variant="outline" onClick={() => void load()} disabled={loading}>应用筛选</Button>{snapshot?.window.provider_id && <span className="pb-2 text-xs text-on-surface-variant">当前：{snapshot.window.provider_id}</span>}</CardContent></Card>
    <div className="mt-6 grid gap-4 md:grid-cols-4">{[['Token', snapshot?.usage.total_tokens ?? '—'], ['调用次数', snapshot?.usage.record_count ?? '—'], ['任务数', snapshot?.tasks.task_count ?? '—'], ['失败任务', snapshot?.tasks.failed ?? '—']].map(([label, value]) => <Card key={label}><CardContent className="pt-5"><div className="text-sm text-on-surface-variant">{label}</div><div className="mt-2 text-2xl font-semibold text-on-surface">{loading && !snapshot ? '…' : value}</div></CardContent></Card>)}</div>
    <Card className="mt-4"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Activity className="h-4 w-4 text-primary" />核心组件</CardTitle></CardHeader><CardContent>{!snapshot ? <div className="py-6 text-sm text-on-surface-variant">{loading ? '正在读取运行状态…' : '暂无运行状态。'}</div> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(snapshot.health.components).map(([name, value]) => { const ok = value === 'healthy'; const unavailable = value === 'unavailable'; return <div key={name} className="rounded-xl border border-border-subtle bg-surface-container-low p-3"><div className="flex items-center gap-2 text-sm font-medium text-on-surface">{ok ? <CheckCircle2 className="h-4 w-4 text-emerald-600" /> : unavailable ? <Server className="h-4 w-4 text-on-surface-variant" /> : <AlertTriangle className="h-4 w-4 text-amber-600" />}{name}</div><div className="mt-2 text-xs text-on-surface-variant">{stateLabel(value)}</div></div> })}</div>}</CardContent></Card>
    <div className="mt-4 grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">供应商用量</CardTitle></CardHeader><CardContent>{snapshot?.providers?.length ? <div className="space-y-2">{snapshot.providers.map(provider => <div key={provider.provider_id} className="flex items-center justify-between gap-3 border-b border-border-subtle py-2 text-sm last:border-0"><div className="min-w-0"><div className="truncate font-medium text-on-surface">{provider.provider_name}</div><div className="text-xs text-on-surface-variant">{provider.call_count} 次调用 · 失败 {provider.failed}</div></div><span className="shrink-0 font-mono text-xs text-on-surface-variant">{provider.total_tokens} tokens</span></div>)}</div> : <span className="text-sm text-on-surface-variant">当前窗口暂无供应商调用。</span>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">任务聚合</CardTitle></CardHeader><CardContent>{snapshot?.task_rows?.length ? <div className="space-y-2">{snapshot.task_rows.slice(0, 8).map(task => <div key={task.task_id} className="flex items-center justify-between gap-3 border-b border-border-subtle py-2 text-sm last:border-0"><div className="min-w-0"><div className="truncate font-medium text-on-surface">{task.task_id}</div><div className="text-xs text-on-surface-variant">{task.call_count} 次调用 · {task.status || '未知状态'}</div></div><span className="shrink-0 font-mono text-xs text-on-surface-variant">{task.total_tokens} tokens</span></div>)}</div> : <span className="text-sm text-on-surface-variant">当前窗口暂无任务记录。</span>}</CardContent></Card></div>
    <Card className="mt-4"><CardHeader><CardTitle className="text-base">插件采集任务</CardTitle></CardHeader><CardContent>{ingestionJobs.length ? <div className="space-y-2">{ingestionJobs.slice(0, 10).map(job => { const latest = job.events[job.events.length - 1]; return <div key={job.job_id} className="flex items-center justify-between gap-3 border-b border-border-subtle py-2 text-sm last:border-0"><div className="min-w-0"><div className="truncate font-medium text-on-surface">{job.job_id}</div><div className="text-xs text-on-surface-variant">{latest?.message || '暂无阶段信息'}{latest?.progress != null ? ` · ${latest.progress}%` : ''}</div></div><span className={job.status === 'failed' ? 'text-error' : job.status === 'completed' ? 'text-emerald-700' : 'text-amber-700'}>{job.status === 'completed' ? '已完成' : job.status === 'failed' ? '失败' : '进行中'}</span></div> })}</div> : <span className="text-sm text-on-surface-variant">暂无插件采集任务。</span>}</CardContent></Card>
    <div className="mt-4 grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">快照状态</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{snapshot ? <><div className="flex items-center gap-2">{health === 'healthy' ? <CheckCircle2 className="h-4 w-4 text-emerald-600" /> : <XCircle className="h-4 w-4 text-amber-600" />}<span>总体状态：{health === 'healthy' ? '正常' : '需关注'}</span></div><div className="text-xs text-on-surface-variant">窗口：{snapshot.window.days} 天 · 截止 {new Date(snapshot.window.end_at).toLocaleString()}</div><div className="text-xs text-on-surface-variant">插件：{snapshot.plugins.ready ? '全部就绪' : `${snapshot.plugins.failed_plugins.length} 个需要处理`}</div></> : <span className="text-on-surface-variant">暂无数据</span>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">运行环境</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-on-surface-variant"><div>后端：{snapshot?.runtime.backend.status ?? '—'} · {snapshot?.runtime.backend.port ?? '—'}</div><div>GPU：{snapshot?.runtime.cuda.available ? snapshot.runtime.cuda.gpu_name : 'CPU 模式'}</div><div>转写：{snapshot?.runtime.whisper.transcriber_type ?? '—'} / {snapshot?.runtime.whisper.model_size ?? '—'}</div><div>MCP：{snapshot?.runtime.mcp.status ?? '—'}</div></CardContent></Card></div>
  </div></div>
}
