import { useEffect, useMemo, useState } from 'react'
import CloudClient, { CloudUser } from '../../services/cloud'
import { CloudUserForm } from '../CloudUserForm'

export function CloudUserList({ client, onChanged }: { client: CloudClient; onChanged?: () => void }) {
  const [users, setUsers] = useState<CloudUser[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | 'active' | 'disabled'>('all'); const [editing, setEditing] = useState<CloudUser | null>(null)
  async function refresh() { try { setUsers(await client.listUsers()); setError(null) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load users') } }
  useEffect(() => { void refresh() }, [client])
  async function remove(user: CloudUser) { if (user.role === 'admin') return; setBusy(user.id); try { await client.deleteUser(user.id); await refresh(); onChanged?.() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to delete user') } finally { setBusy(null) } }
  const visibleUsers = useMemo(() => users.filter(user => (!query.trim() || user.username.toLowerCase().includes(query.trim().toLowerCase())) && (status === 'all' || (status === 'disabled' ? user.disabled : !user.disabled))), [query, status, users])
  if (error && !users.length) return <section role="alert" className="p-3 text-sm text-red-700">{error}</section>
  if (!users.length) return <section role="status" className="p-4 text-sm text-slate-500">No cloud users.</section>
  return <section aria-labelledby="user-list-title" className="p-3"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 id="user-list-title" className="text-base font-semibold">Cloud users</h2><span className="text-xs text-slate-500">{visibleUsers.length} / {users.length}</span></div><div className="mb-3 flex flex-wrap gap-2"><input aria-label="Search users" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search username" className="min-w-48 flex-1 rounded border border-slate-300 px-3 py-2 text-sm" /><select aria-label="Filter user status" value={status} onChange={event => setStatus(event.target.value as typeof status)} className="rounded border border-slate-300 px-3 py-2 text-sm"><option value="all">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="px-3 py-2">User</th><th className="px-3 py-2">Role</th><th className="px-3 py-2">Status</th><th className="sticky right-0 bg-white px-3 py-2 text-right">Actions</th></tr></thead><tbody>{visibleUsers.map(user => <tr key={user.id} className="border-b border-slate-100"><td className="px-3 py-3 font-medium">{user.username}</td><td className="px-3 py-3 text-slate-500">{user.role}</td><td className="px-3 py-3 text-slate-500">{user.disabled ? 'Disabled' : 'Active'}</td><td className="sticky right-0 whitespace-nowrap bg-white px-3 py-3 text-right"><button type="button" disabled={user.role === 'admin'} onClick={() => setEditing(user)} className="mr-3 text-xs text-slate-700 underline disabled:text-slate-300">Edit</button>{user.role === 'user' ? <button type="button" disabled={busy === user.id} onClick={() => void remove(user)} className="text-xs text-red-700 underline disabled:opacity-50">Delete</button> : <span className="text-xs text-slate-400">Protected</span>}</td></tr>)}</tbody></table></div>{!visibleUsers.length && <p role="status" className="py-5 text-sm text-slate-500">No matching users.</p>}{editing && <div className="mt-3 rounded border border-slate-200 bg-slate-50"><CloudUserForm client={client} user={editing} onSaved={() => { setEditing(null); void refresh(); onChanged?.() }} /></div>}{error ? <p role="alert" className="mt-2 text-sm text-red-700">{error}</p> : null}</section>
}
