import { useEffect, useState } from 'react'
import CloudClient from '../../services/cloud'

type ShareToken = { id: string; role: string; scopes: string[]; expires_at?: number | null; revoked_at?: number | null }

export function CloudSharePanel({ client, sessionId }: { client: CloudClient; sessionId: string }) {
  const [tokens, setTokens] = useState<ShareToken[]>([]); const [newToken, setNewToken] = useState<string | null>(null); const [role, setRole] = useState<'viewer' | 'standard'>('viewer'); const [expiry, setExpiry] = useState<'permanent' | 'hour' | 'day'>('permanent'); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  async function refresh() { try { setTokens(await client.listShareTokens(sessionId) as ShareToken[]); setError(null) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load share tokens') } }
  useEffect(() => { void refresh() }, [sessionId])
  async function create() { setBusy(true); setError(null); try { const expiresAt = expiry === 'permanent' ? undefined : Math.floor(Date.now() / 1000) + (expiry === 'hour' ? 3600 : 86400); const scopes = role === 'viewer' ? ['event.receive'] : ['event.receive', 'message.send']; const result = await client.createShareToken(sessionId, role, scopes, expiresAt); setNewToken(result.token); await refresh() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create share token') } finally { setBusy(false) } }
  async function revoke(id: string) { setBusy(true); try { await client.revokeShareToken(id); await refresh() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to revoke share token') } finally { setBusy(false) } }
  return <section aria-labelledby="share-title" className="space-y-3 p-3"><div><h2 id="share-title" className="text-base font-semibold">Share session</h2><p className="text-sm text-slate-500">Permissions and expiry are independent. Viewer links never grant control.</p></div><div className="grid gap-2 sm:grid-cols-2"><label className="text-sm">Permission<select value={role} onChange={event => setRole(event.target.value as 'viewer' | 'standard')} className="mt-1 block w-full rounded border border-slate-300 px-2 py-1"><option value="viewer">Viewer (read-only)</option><option value="standard">Standard (send messages)</option></select></label><label className="text-sm">Expires<select value={expiry} onChange={event => setExpiry(event.target.value as 'permanent' | 'hour' | 'day')} className="mt-1 block w-full rounded border border-slate-300 px-2 py-1"><option value="permanent">Never</option><option value="hour">In 1 hour</option><option value="day">In 24 hours</option></select></label></div><button type="button" disabled={busy} onClick={() => void create()} className="rounded bg-slate-900 px-3 py-2 text-sm text-white disabled:opacity-50">Create share token</button>{newToken ? <div role="status" className="rounded bg-slate-100 p-3"><p className="text-xs text-slate-500">Copy this token now. It will not be shown again.</p><code className="mt-1 block break-all text-xs">{newToken}</code></div> : null}{tokens.length ? <ul role="list" className="space-y-2">{tokens.map(token => <li key={token.id} className="flex items-center justify-between rounded border border-slate-200 p-2 text-sm"><span>{token.role} · {token.expires_at ? `expires ${new Date(token.expires_at * 1000).toLocaleString()}` : 'never expires'} · {token.revoked_at ? 'Revoked' : 'Active'}</span><button type="button" disabled={busy || Boolean(token.revoked_at)} onClick={() => void revoke(token.id)} className="rounded border border-red-200 px-2 py-1 text-xs text-red-700 disabled:opacity-50">Revoke</button></li>)}</ul> : <p role="status" className="text-sm text-slate-500">No share tokens.</p>}{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}</section>
}
