import { useState } from 'react'
import CloudClient, { CloudUser } from '../../services/cloud'

export function CloudUserForm({ client, user, onSaved }: { client: CloudClient; user?: CloudUser; onSaved?: () => void }) {
  const [username, setUsername] = useState(user?.username ?? ''); const [password, setPassword] = useState(''); const [disabled, setDisabled] = useState(user?.disabled ?? false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [inviteLink, setInviteLink] = useState('')
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { if (user) await client.updateUser(user.id, { username, ...(password ? { password } : {}), disabled }); else { const created = await client.createUser(username, password); setInviteLink(`${window.location.origin}/cloud?invite=${encodeURIComponent(created.id)}`) }; setPassword(''); onSaved?.() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save user') } finally { setBusy(false) } }
  const copyInvite = () => { if (!inviteLink) return; void navigator.clipboard?.writeText(inviteLink); }
  return <form onSubmit={submit} aria-labelledby="user-form-title" className="flex max-w-md flex-col gap-3 p-3"><h2 id="user-form-title" className="text-base font-semibold">{user ? 'Edit cloud user' : 'Invite cloud user'}</h2><label htmlFor="cloud-user-name" className="text-sm font-medium">Username or email</label><input id="cloud-user-name" required value={username} onChange={event => setUsername(event.target.value)} className="rounded border border-slate-300 px-3 py-2" /><label htmlFor="cloud-user-password" className="text-sm font-medium">{user ? 'New password (optional)' : 'Temporary password'}</label><input id="cloud-user-password" type="password" autoComplete="new-password" required={!user} value={password} onChange={event => setPassword(event.target.value)} className="rounded border border-slate-300 px-3 py-2" />{user ? <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={disabled} onChange={event => setDisabled(event.target.checked)} /> Disabled</label> : null}<button type="submit" disabled={busy || !username || (!user && !password)} className="rounded bg-slate-900 px-3 py-2 text-sm text-white disabled:opacity-50">{busy ? 'Saving…' : user ? 'Save user' : 'Send invitation'}</button>{inviteLink && <div role="status" className="rounded border border-emerald-200 bg-emerald-50 p-3 text-xs"><p>邀请已创建，可复制链接发送给目标用户。</p><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 break-all">{inviteLink}</code><button type="button" onClick={copyInvite} className="shrink-0 underline">复制</button></div></div>}{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}</form>
}
