import { useState } from 'react'
import CloudClient from '../../services/cloud'

export function CloudPairingPanel({ client, onPaired }: { client: CloudClient; onPaired?: () => void }) {
  const [code, setCode] = useState('')
  const [deviceId, setDeviceId] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [message, setMessage] = useState<string | null>(null)
  async function start() { setBusy(true); setError(null); setMessage(null); try { const result = await client.startPairing(); setCode(result.code); setMessage('Share this code with the device you want to connect.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to start pairing') } finally { setBusy(false) } }
  async function confirm() { setBusy(true); setError(null); setMessage(null); try { await client.confirmPairing(code, deviceId, 'web', displayName); setMessage('Device paired successfully.'); onPaired?.() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to confirm pairing') } finally { setBusy(false) } }
  return <section aria-labelledby="cloud-pairing-title" className="flex max-w-md flex-col gap-4 p-4"><div><h2 id="cloud-pairing-title" className="text-lg font-semibold text-slate-900">Connect a device</h2><p className="text-sm text-slate-500">Use a short-lived code to pair another NoteMeld device.</p></div><button type="button" disabled={busy} onClick={() => void start()} className="rounded border border-slate-300 px-3 py-2 text-sm">{busy ? 'Working…' : 'Generate pairing code'}</button>{code ? <output aria-label="Pairing code" className="rounded bg-slate-100 p-3 text-center font-mono text-xl tracking-widest">{code}</output> : null}<div className="flex flex-col gap-2"><label htmlFor="pairing-code" className="text-sm font-medium">Pairing code</label><input id="pairing-code" value={code} onChange={event => setCode(event.target.value)} className="rounded border border-slate-300 px-3 py-2" /><label htmlFor="pairing-device" className="text-sm font-medium">Target device ID</label><input id="pairing-device" required value={deviceId} onChange={event => setDeviceId(event.target.value)} className="rounded border border-slate-300 px-3 py-2" /><label htmlFor="pairing-name" className="text-sm font-medium">Display name</label><input id="pairing-name" required value={displayName} onChange={event => setDisplayName(event.target.value)} className="rounded border border-slate-300 px-3 py-2" /><button type="button" disabled={busy || !code || !deviceId || !displayName} onClick={() => void confirm()} className="rounded bg-slate-900 px-3 py-2 text-sm text-white disabled:opacity-50">Confirm pairing</button></div>{message ? <p role="status" className="text-sm text-slate-600">{message}</p> : null}{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}</section>
}
